### ISSUE TITLE
Allow to pass properties files for Petals components

### ISSUE THREAD

**Issue by vincent-zurczak** [petalslink/docker-petals-deployer#5]
How would we address the following use case: `petals-cli -u http://... -D propertiesFile=/tmp/test.properties`?

We should be able to do it... :thinking:

**Comment by psouquet** [comment]
Could we use two different separators, one of them being optional ? :
`-e DEPLOY_URL="url1§prop1;url2;url3;url4§prop4"`
(with something better than `§` obviously)

Which would translate to : 
```
petals-cli -u url1 -D prop1
petals-cli -u url2
petals-cli -u url3
petals-cli -u url4 -D prop4
```

Note: in this case, I think we'd have to use bash instead of shell (can't use nested `$*` ...). I wasn't able to run `docker-wrapper.sh` in bash from docker (but I guess its possible), fallback always possible is to call a bash deploy script from `docker-wrapper.sh`
